### ISSUE TITLE
No opportunity to add 'CoroutineExceptionHandler' to 'viewModelScope' in KViewModel

### ISSUE THREAD

**Issue by VitalyPeryatin** [adeo-opensource/kviewmodel--mpp#13]
<img width="648" alt="image" src="https://user-images.githubusercontent.com/22561563/200061267-28bf018a-fac3-490a-a155-75ce049c3a2c.png">

**Comment by VitalyPeryatin** [comment]
PR with fix: https://github.com/adeo-opensource/kviewmodel--mpp/pull/15

**Comment by Skeptick** [comment]
Available in [0.12](https://github.com/adeo-opensource/kviewmodel--mpp/releases/tag/0.12)
