### ISSUE TITLE
Add ios target for using library with Compose for iOS

### ISSUE THREAD

**Issue by VitalyPeryatin** [adeo-opensource/kviewmodel--mpp#17]
Add ios target to `multiplatform-compose-setup` for using library with Compose for iOS. It is impossible to use these dependencies in project with Compose for iOS without this target: 
- kviewmodel-compose
- kviewmodel-odyssey
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/22561563/209458764-c47a3df7-ee94-4100-a0fc-b45f7ea59ce9.png">

**Comment by Skeptick** [comment]
Done in https://github.com/adeo-opensource/kviewmodel--mpp/pull/18
